# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export TERM=xterm-256color

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Reload history from file - for tmux
[ -f "$HISTFILE" ] && fc -R "$HISTFILE"

# Persist shell history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory           # Append to the history file (do not overwrite)
setopt incappendhistory       # Add commands as they are typed, not at shell exit
setopt sharehistory           # Share history across all sessions
setopt histignoredups         # Ignore duplicated commands
setopt histignorespace        # Ignore commands starting with space
setopt extendedhistory        # Save timestamp + duration in history file

autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'

# Load system specific zsh file
if [ -f ~/.zshrc_system ]; then
    source ~/.zshrc_system
fi

# Set backspace
bindkey "^[[3~" delete-char

export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:$ANDROID_HOME/emulator

export PATH="$PATH:$HOME/.local/bin"
alias compose-restart="docker compose down && docker compose up -d"
# Hey YOU - Don't add non generic things here!

[[ -s "/home/jake/.gvm/scripts/gvm" ]] && source "/home/jake/.gvm/scripts/gvm"
unset -f cd
